/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MetaPane: typeof import('./src/components/MetaPane.vue')['default']
    Models: typeof import('./src/views/Models.vue')['default']
    OidcCallback: typeof import('./src/views/oidc/OidcCallback.vue')['default']
    OidcCallbackSilent: typeof import('./src/views/oidc/OidcCallbackSilent.vue')['default']
    OrbitSettings: typeof import('./src/components/settings/OrbitSettings.vue')['default']
    PickerSettings: typeof import('./src/components/settings/PickerSettings.vue')['default']
    PropsPane: typeof import('./src/components/PropsPane.vue')['default']
    RenderManagerSettings: typeof import('./src/components/settings/RenderManagerSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsLine: typeof import('./src/components/SettingsLine.vue')['default']
    SettingsPane: typeof import('./src/components/SettingsPane.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
    Viewer: typeof import('./src/views/Viewer.vue')['default']
  }
}
